### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by tyhi** [Shinyylel/pagbot-website#1]
this site bunk af
![Screenshot 2022-08-23 at 08-35-19 https __pagbot-website vercel app](https://user-images.githubusercontent.com/31829732/186172175-f671d306-d508-4155-8c1c-5485c0150fa7.png)

**Comment by steele123** [comment]
:trollface:

**Comment by nickmharrison** [comment]
:trollface:

**Comment by tyhi** [comment]
requesting reopen as it is worse than before :(
![Screenshot 2022-08-24 at 08-03-58 https __pagbot-website vercel app](https://user-images.githubusercontent.com/31829732/186425691-40532fdc-5bda-40ae-bb27-c18f4a002cb0.png)
